language: python
python:
  - "3.6"
env:
  global:
    - ENV='Testing'
  services:
    - postgresql
before_script:
  - "psql -c 'create database ireporter_test_db;' -U postgres"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run -m pytest
  - coverage report
after_success:
  - coveralls